// Generated by tools/hgss_import/import_kanto_music.py, do not edit.
#ifndef POKEPLATINUM_DATA_KANTO_SOUND_H
#define POKEPLATINUM_DATA_KANTO_SOUND_H

#define KANTO_BGM_BANK_FIRST BANK_KANTO_GS_BICYCLE_sbnk
#define KANTO_BGM_BANK_LAST  BANK_KANTO_PL_BICYCLE_sbnk

#define KANTO_SURF_BGM SEQ_KANTO_GS_NAMINORI_sseq
#define KANTO_BICYCLE_BGM SEQ_KANTO_GS_BICYCLE_sseq

#endif
