// Generated by tools/hgss_import/import_kanto_music.py, do not edit.
#ifndef POKEPLATINUM_DATA_KANTO_SOUND_H
#define POKEPLATINUM_DATA_KANTO_SOUND_H

#define KANTO_BGM_BANK_FIRST BANK_KANTO_GS_CHAMPROAD_sbnk
#define KANTO_BGM_BANK_LAST  BANK_KANTO_PL_BICYCLE_sbnk

#endif
