prop_animation_files = copy_gen.process(files(
    'prop_animation_000.nsbta',
    'prop_animation_001.nsbca',
    'prop_animation_002.nsbca',
    'prop_animation_003.nsbca',
    'prop_animation_004.nsbta',
    'prop_animation_005.nsbca',
    'prop_animation_006.nsbca',
    'prop_animation_007.nsbca',
    'prop_animation_008.nsbca',
    'prop_animation_009.nsbca',
    'prop_animation_010.nsbca',
    'prop_animation_011.nsbtp',
    'prop_animation_012.nsbtp',
    'prop_animation_013.nsbtp',
    'prop_animation_014.nsbta',
    'prop_animation_015.nsbtp',
    'prop_animation_016.nsbtp',
    'prop_animation_017.nsbtp',
    'prop_animation_018.nsbta',
    'prop_animation_019.nsbta',
    'prop_animation_020.nsbta',
    'prop_animation_021.nsbta',
    'prop_animation_022.nsbta',
    'prop_animation_023.nsbtp',
    'prop_animation_024.nsbtp',
    'prop_animation_025.nsbca',
    'prop_animation_026.nsbca',
    'prop_animation_027.nsbca',
    'prop_animation_028.nsbca',
    'prop_animation_029.nsbca',
    'prop_animation_030.nsbca',
    'prop_animation_031.nsbtp',
    'prop_animation_032.nsbtp',
    'prop_animation_033.nsbca',
    'prop_animation_034.nsbca',
    'prop_animation_035.nsbta',
    'prop_animation_036.nsbta',
    'prop_animation_037.nsbta',
    'prop_animation_038.nsbta',
    'prop_animation_039.nsbca',
    'prop_animation_040.nsbca',
    'prop_animation_041.nsbtp',
    'prop_animation_042.nsbtp',
    'prop_animation_043.nsbta',
    'prop_animation_044.nsbta',
    'prop_animation_045.nsbta',
    'prop_animation_046.nsbta',
    'prop_animation_047.nsbta',
    'prop_animation_048.nsbta',
    'prop_animation_049.nsbca',
    'prop_animation_050.nsbtp',
    'prop_animation_051.nsbtp',
    'prop_animation_052.nsbtp',
    'prop_animation_053.nsbta',
    'prop_animation_054.nsbca',
    'prop_animation_055.nsbta',
    'prop_animation_056.nsbta',
    'prop_animation_057.nsbta',
    'prop_animation_058.nsbta',
    'prop_animation_059.nsbta',
    'prop_animation_060.nsbta',
    'prop_animation_061.nsbta',
    'prop_animation_062.nsbta',
    'prop_animation_063.nsbta',
    'prop_animation_064.nsbtp',
    'prop_animation_065.nsbca',
    'prop_animation_066.nsbca',
    'prop_animation_067.nsbca',
    'prop_animation_068.nsbta',
    'prop_animation_069.nsbca',
    'prop_animation_070.nsbca',
    'prop_animation_071.nsbta',
    'prop_animation_072.nsbtp',
    'prop_animation_073.nsbca',
    'prop_animation_074.nsbta',
    'prop_animation_075.nsbta',
    'prop_animation_076.nsbca',
    'prop_animation_077.nsbta',
    'prop_animation_078.nsbta',
    'prop_animation_079.nsbta',
    'prop_animation_080.nsbca',
    'prop_animation_081.nsbca',
    'prop_animation_082.nsbta',
    'prop_animation_083.nsbta',
    'prop_animation_084.nsbtp',
    'prop_animation_085.nsbta',
    'prop_animation_086.nsbta',
    'prop_animation_087.nsbtp',
    'prop_animation_088.nsbta',
    'prop_animation_089.nsbta',
    'prop_animation_090.nsbta',
    'prop_animation_091.nsbtp',
    'prop_animation_092.nsbtp',
    'prop_animation_093.nsbca',
    'prop_animation_094.nsbtp',
    'prop_animation_095.nsbta',
    'prop_animation_096.nsbca',
    'prop_animation_097.nsbtp',
    'kanto_bm_anime_035.nsbca',
    'kanto_bm_anime_036.nsbca',
    'kanto_bm_anime_121.nsbta',
    'kanto_bm_anime_122.nsbta',
    'kanto_bm_anime_001.nsbca',
    'kanto_bm_anime_002.nsbca',
    'kanto_bm_anime_005.nsbca',
    'kanto_bm_anime_006.nsbta',
    'kanto_bm_anime_003.nsbca',
    'kanto_bm_anime_009.nsbta',
    'kanto_bm_anime_061.nsbta',
    'kanto_bm_anime_067.nsbca',
    'kanto_bm_anime_068.nsbta',
    'kanto_bm_anime_078.nsbca',
    'kanto_bm_anime_079.nsbca',
    'kanto_bm_anime_080.nsbca',
    'kanto_bm_anime_081.nsbca',
    'kanto_bm_anime_200.nsbtp',
    'kanto_bm_anime_201.nsbtp',
    'kanto_bm_anime_097.nsbtp',
    'kanto_bm_anime_084.nsbtp',
    'kanto_bm_anime_085.nsbta',
    'kanto_bm_anime_099.nsbtp',
    'kanto_bm_anime_100.nsbca',
    'kanto_bm_anime_101.nsbca',
    'kanto_bm_anime_152.nsbta',
    'kanto_bm_anime_153.nsbta',
    'kanto_bm_anime_154.nsbta',
    'kanto_bm_anime_155.nsbta',
    'kanto_bm_anime_244.nsbta',
    'kanto_bm_anime_245.nsbtp',
    'kanto_bm_anime_250.nsbtp',
    'kanto_bm_anime_251.nsbtp',
    'kanto_bm_anime_246.nsbta',
    'kanto_bm_anime_247.nsbta',
    'kanto_bm_anime_248.nsbta',
    'kanto_bm_anime_249.nsbta',
    'kanto_bm_anime_110.nsbca',
    'kanto_bm_anime_111.nsbca',
    'kanto_bm_anime_123.nsbca',
    'kanto_bm_anime_124.nsbca',
    'kanto_bm_anime_125.nsbca',
    'kanto_bm_anime_126.nsbca',
    'kanto_bm_anime_182.nsbta',
    'kanto_bm_anime_183.nsbta',
    'kanto_bm_anime_184.nsbta',
    'kanto_bm_anime_185.nsbta',
    'kanto_bm_anime_156.nsbtp',
    'kanto_bm_anime_157.nsbtp',
    'kanto_bm_anime_158.nsbtp',
    'kanto_bm_anime_159.nsbtp',
    'kanto_bm_anime_187.nsbtp',
    'kanto_bm_anime_188.nsbtp',
    'kanto_bm_anime_189.nsbtp',
    'kanto_bm_anime_190.nsbtp',
    'kanto_bm_anime_191.nsbca',
    'kanto_bm_anime_207.nsbca',
    'kanto_bm_anime_208.nsbca',
    'kanto_bm_anime_209.nsbca',
    'kanto_bm_anime_210.nsbca',
    'kanto_bm_anime_232.nsbta',
    'kanto_bm_anime_233.nsbta',
    'kanto_bm_anime_234.nsbta',
    'kanto_bm_anime_235.nsbta',
    'kanto_bm_anime_236.nsbta',
    'kanto_bm_anime_237.nsbtp',
    'kanto_bm_anime_254.nsbta',
    'kanto_bm_anime_255.nsbta',
    'kanto_bm_anime_256.nsbta',
    'kanto_bm_anime_257.nsbta',
    'kanto_bm_anime_262.nsbca',
    'kanto_bm_anime_263.nsbca',
    'kanto_bm_anime_264.nsbca',
    'kanto_bm_anime_265.nsbca',
    'kanto_bm_anime_095.nsbtp',
    'kanto_bm_anime_096.nsbca',
    'kanto_bm_anime_062.nsbtp',
    'kanto_bm_anime_063.nsbtp',
    'kanto_bm_anime_031.nsbta',
    'kanto_bm_anime_032.nsbta',
    'kanto_bm_anime_102.nsbtp',
    'kanto_bm_anime_103.nsbtp',
    'kanto_bm_anime_008.nsbtp',
    'kanto_bm_anime_219.nsbca',
    'kanto_bm_anime_220.nsbca',
    'kanto_bm_anime_180.nsbca',
    'kanto_bm_anime_007.nsbtp',
    'kanto_bm_anime_045.nsbtp',
    'kanto_bm_anime_046.nsbta',
    'kanto_bm_anime_047.nsbta',
    'kanto_bm_anime_088.nsbta',
    'kanto_bm_anime_107.nsbtp',
    'kanto_bm_anime_106.nsbtp',
    'kanto_bm_anime_113.nsbca',
    'kanto_bm_anime_114.nsbta',
    'kanto_bm_anime_129.nsbta',
    'kanto_bm_anime_181.nsbca',
    'kanto_bm_anime_192.nsbta',
    'kanto_bm_anime_193.nsbtp',
    'kanto_bm_anime_194.nsbca',
    'kanto_bm_anime_195.nsbta',
    'kanto_bm_anime_196.nsbtp',
    'kanto_bm_anime_197.nsbca',
    'kanto_bm_anime_198.nsbta',
    'kanto_bm_anime_199.nsbta',
    'kanto_bm_anime_202.nsbta',
    'kanto_bm_anime_203.nsbca',
    'kanto_bm_anime_206.nsbta',
    'kanto_bm_anime_221.nsbta',
    'kanto_bm_anime_224.nsbta',
    'kanto_bm_anime_225.nsbta',
    'kanto_bm_anime_227.nsbta',
    'kanto_bm_anime_252.nsbca',
    'kanto_bm_anime_253.nsbma',
    'kanto_bm_anime_258.nsbta',
    'kanto_bm_anime_259.nsbta',
    'kanto_bm_anime_261.nsbca',
    'kanto_bm_anime_266.nsbta',
    'kanto_bm_anime_267.nsbtp',
    'kanto_bm_anime_268.nsbta',
    'kanto_bm_anime_269.nsbtp',
    'kanto_bm_anime_270.nsbta',
    'kanto_bm_anime_271.nsbma',
    'kanto_bm_anime_272.nsbca',
    'kanto_ground_anime_000.nsbta',
    'kanto_ground_anime_001.nsbta',
))

prop_animation_narc = custom_target('prop_animations.narc',
    output: 'prop_animations.narc',
    input: prop_animation_files,
    command: [
        nitroarc_exe,
        '--create',
        '--files-from', files('prop_animations.order'),
        '--file', '@OUTPUT0@',
        '@PRIVATE_DIR@',
    ],
)

nitrofs_files += prop_animation_narc
