#!/usr/bin/env python3
"""Import the signs, NPCs, items and scripts of HGSS's Kanto maps.

- Text: each Kanto message bank becomes a Platinum text bank (kanto_text.py).
- Signs: HGSS's signpost graphics replace Platinum's (kanto_signs.py).
- Events: objects, signs, hidden items and triggers join the warps that
  import_kanto_world.py wrote. Sprites come from kanto_sprites.json.
- Scripts: each map's scripts are translated to Platinum's script commands
  (kanto_scripts.py). Scripts that need something Platinum lacks get a stand-in;
  kanto_scripts_report.txt lists them.
- Items: item balls join Platinum's visible items scripts, hidden items its
  hidden items table, and Kanto's specialty marts its marts.
- Flags and vars: HGSS's are given Platinum flags and vars that only Sinnoh's
  map scripts used (kanto_vars_flags.json records which). Kanto's flags that
  HGSS sets when a game starts are set by Platinum's new game script too.

Trainers are not imported yet: trainer NPCs stand where HGSS has them, without
battling.

Run after import_kanto_world.py and import_kanto_sprites.py. Usage:
tools/hgss_import/import_kanto_scripts.py <path-to-pokeheartgold>
"""
import argparse
import collections
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import kanto_signs  # noqa: E402
import kanto_text  # noqa: E402
from hgss_headers import load_headers  # noqa: E402
from import_kanto import matrix_key  # noqa: E402
from import_kanto_world import WORLD_OFFSET_X, WORLD_OFFSET_Z, events_name, header_name  # noqa: E402
from kanto_scripts import FileContext, Translator, Unsupported  # noqa: E402
from meson_lists import update_meson_files, update_order  # noqa: E402

HERE = Path(__file__).parent
PL = HERE.parents[1]
SCRIPTS = PL / "res/field/scripts"
EVENTS = PL / "res/field/events"
GENERATED_BEGIN = "    // Kanto (generated by tools/hgss_import/import_kanto_scripts.py)"
GENERATED_END = "    // End of Kanto"

# HGSS movement types share Platinum's numbering up to here.
LAST_SHARED_MOVEMENT_TYPE = 47
# HGSS's field move objects -> (Platinum sprite, Platinum script).
FIELD_MOVE_OBJECTS = {
    "std_field_cut": 10000,
    "std_field_rock_smash": 10001,
    "std_field_strength": 10002,
}
# HGSS's fanfares -> Platinum's.
FANFARES = {
    "SEQ_ME_ITEM": "SEQ_FANFA4", "SEQ_ME_KEYITEM": "SEQ_FANFA3", "SEQ_ME_BADGE": "SEQ_BADGE",
    "SEQ_ME_LVUP": "SEQ_FANFA1", "SEQ_ME_ASA": "SEQ_ASA", "SEQ_ME_POKEGET": "SEQ_FANFA5",
}
# Platinum's vars and flags with uses outside Sinnoh's map scripts that a
# name search doesn't find (they're reached by number).
RESERVED = re.compile(r"HIDDEN_LOCATION|DISTRIBUTION|BATTLE|FOLLOWER|RESTAURANT|FIVE_MAID|ELEVATOR|LOTTERY|"
                      r"CATCHING|POKEMON_NEWS|ACCESSORY|TURNBACK|REVIVED|UNDERGROUND|PAL_PARK|CONTEST|"
                      r"POKETCH|AMITY|VILLA|GALACTIC_HQ|DAILY")


def read_lines(path):
    return [l.strip() for l in path.read_text().splitlines() if l.strip()]


def pl_constants():
    """Identifiers Platinum's script macros know (approximately)."""
    names = set()
    inc = (PL / "asm/macros/scrcmd.inc").read_text()
    for m in re.finditer(r'#include "generated/(\w+)\.h"', inc):
        path = PL / "generated" / f"{m.group(1)}.txt"
        if path.exists():
            names |= {l.split("=")[0].strip() for l in read_lines(path)}
    for m in re.finditer(r'#include "(constants/[\w/]+\.h)"', inc):
        path = PL / "include" / m.group(1)
        if path.exists():
            text = path.read_text()
            names |= set(re.findall(r"#define\s+(\w+)", text))
            names |= set(re.findall(r"^\s+([A-Z][A-Z0-9_]+)\s*[,=]", text, re.M))
    names |= {l.split("=")[0].strip() for l in read_lines(PL / "generated/vars_flags.txt")}
    names |= {l for l in read_lines(PL / "generated/species.txt")}
    return names


def pl_vars_flags():
    """Platinum's flag and var names by number (the first name of each)."""
    values, by_value, current = {}, {}, 0
    for line in read_lines(PL / "generated/vars_flags.txt"):
        name, _, value = (p.strip() for p in line.partition("="))
        if value and not name.startswith(("FLAG_", "VAR_")) and value.startswith(("FLAG_", "VAR_")):
            # An end marker naming the last flag or var.
            values[name] = values[value]
            continue
        if value:
            current = int(value) if value.isdigit() else values[value]
        values[name] = current
        if name.startswith(("FLAG_", "VAR_")):
            by_value.setdefault(current, name)
            current += 1
    return by_value


def hgss_defines(path):
    out = {}
    for line in path.read_text().splitlines():
        m = re.match(r"#define\s+(\w+)\s+(0x[0-9A-Fa-f]+|\d+)\b", line)
        if m:
            out[m.group(1)] = int(m.group(2), 0)
    return out


class Names:
    """Translates the names HGSS's scripts and events use."""

    def __init__(self, hg, kanto_sprites, free):
        self.hg = hg
        self.known = pl_constants()
        self.flags = hgss_defines(hg / "include/constants/flags.h")
        self.vars = hgss_defines(hg / "include/constants/vars.h")
        self.sprites = kanto_sprites
        self.sounds = self.read_sounds()
        self.free_flags = list(free["flags"])
        self.free_vars = list(free["vars"])
        self.free_daily = [f for f in read_lines(PL / "generated/vars_flags.txt") if re.fullmatch(r"FLAG_DAILY_0x[0-9A-F]+", f)]
        self.flag_map, self.var_map = {}, {}
        self.pl_names = pl_vars_flags()
        self.fly_flags = self.read_fly_flags()
        self.messages = set()
        self.objects = set()
        self.marts = {}
        self.unsupported_names = collections.Counter()
        self.badges = hgss_defines(hg / "include/constants/badge.h")
        self.kanto_maps = {}  # HGSS map -> (Platinum header, on the world map)

    @staticmethod
    def read_sounds():
        """Sequence name -> the constant scripts use, which names its file."""
        seqs = json.loads((PL / "res/sound/pl_sound_data.json").read_text())["seqInfo"]
        naix = PL / "build/res/sound/pl_sound_data.naix"
        by_id = {int(v): k for k, v in re.findall(r"#define (\w+) (\d+)", naix.read_text())}
        return {s["name"]: by_id[i] for i, s in enumerate(seqs) if s.get("name") and i in by_id}

    def read_fly_flags(self):
        text = (PL / "src/applications/town_map/fly_locations.c").read_text()
        pairs = re.findall(r"\.mapHeader = (MAP_HEADER_KANTO_\w+),\s*\.unusedUnlockFirstArrivalFlag = (FIRST_ARRIVAL_\w+)", text)
        return {h.removeprefix("MAP_HEADER_KANTO_"): "FLAG_" + f for h, f in pairs}

    # ------------------------------------------------------------- flags/vars
    def flag(self, name):
        if name in self.flag_map:
            return self.flag_map[name]
        value = self.flags.get(name)
        if value is None:
            raise Unsupported(name)
        if value == 0:
            out = "0"
        elif value < 0x40:
            out = self.pl_names[value]
        elif 0xAA0 <= value < 0xAA0 + 192:
            out = self.free_daily.pop()
        elif name == "FLAG_GAME_CLEAR":
            out = "FLAG_GAME_COMPLETED"
        elif name.startswith("FLAG_SYS_FLYPOINT_") and name.removeprefix("FLAG_SYS_FLYPOINT_") in self.fly_flags:
            out = self.fly_flags[name.removeprefix("FLAG_SYS_FLYPOINT_")]
        elif 0x550 <= value < 0x830:
            raise Unsupported(f"trainer flag {name}")
        else:
            if not self.free_flags:
                raise Unsupported(f"out of flags for {name}")
            out = self.free_flags.pop(0)
        self.flag_map[name] = out
        return out

    def var(self, name):
        if name in self.var_map:
            return self.var_map[name]
        value = self.vars.get(name)
        if value is None:
            raise Unsupported(name)
        if 0x4000 <= value < 0x4020:
            out = self.pl_names[value]
        elif 0x4020 <= value < 0x4030:
            out = self.pl_names[value]
        elif name == "VAR_SPECIAL_RESULT":
            out = "VAR_RESULT"
        elif name == "VAR_SPECIAL_LAST_TALKED":
            out = "VAR_LAST_TALKED"
        elif 0x8000 <= value <= 0x800B:
            out = f"VAR_0x{value:04X}"
        elif 0x4030 <= value < 0x8000:
            if not self.free_vars:
                raise Unsupported(f"out of vars for {name}")
            out = self.free_vars.pop(0)
        else:
            raise Unsupported(name)
        self.var_map[name] = out
        return out

    # ------------------------------------------------------------------ names
    def value(self, token):
        token = token.strip()
        if re.fullmatch(r"-?(0x[0-9A-Fa-f]+|\d+)", token):
            return token
        if re.fullmatch(r"\w+", token):
            return self.name(token)
        # An expression: translate each name in it.
        return re.sub(r"[A-Za-z_]\w*", lambda m: self.name(m.group(0)), token)

    def name(self, n):
        if n.startswith("FLAG_"):
            return self.flag(n)
        if n.startswith("VAR_"):
            return self.var(n)
        if n == "obj_player":
            return "LOCALID_PLAYER"
        if n.startswith("obj_"):
            if n not in self.objects:
                raise Unsupported(n)
            return n
        if n.startswith("msg_"):
            return self.message(n)
        if n.startswith("SPRITE_"):
            gfx = self.sprites.get(n)
            if n.startswith("SPRITE_VAR_"):
                gfx = f"OBJ_EVENT_GFX_VAR_{int(n.removeprefix('SPRITE_VAR_')):X}"
            if gfx is None:
                raise Unsupported(n)
            return gfx
        if n == "RGB_BLACK":
            return "COLOR_BLACK"
        if n == "RGB_WHITE":
            return "COLOR_WHITE"
        if n in ("TRUE", "FALSE"):
            return n
        if n.startswith(("MAP_", "TRAINER_", "BADGE_")):
            raise Unsupported(n)
        if n in self.known:
            return n
        self.unsupported_names[n] += 1
        raise Unsupported(n)

    def message(self, m):
        if re.fullmatch(r"\d+", m):
            return m
        if m not in self.messages:
            raise Unsupported(f"message {m}")
        return m

    def sound(self, s):
        return self.sounds.get(s)

    def fanfare(self, s):
        f = FANFARES.get(s)
        return self.sounds.get(f)

    def badge_number(self, b):
        if re.fullmatch(r"\d+|0x[0-9a-fA-F]+", b):
            return int(b, 0)
        return self.badges.get(b)

    def badge(self, b):
        """HGSS's badges 8 to 15 are Kanto's; Platinum has 8."""
        value = self.badge_number(b)
        if value is None or not 8 <= value < 16:
            raise Unsupported(f"badge {b}")
        return str(value - 8)

    def badge_check(self, b, var):
        value = self.badge_number(b)
        if value is not None and value < 8:
            # Johto's badges: HGSS's player has them all in Kanto.
            return [f"SetVar {var}, 1"]
        return [f"CheckBadgeAcquired {self.badge(b)}, {var}"]

    def trainer(self, t):
        raise Unsupported(f"trainer {t}")

    def mart(self, n):
        self.marts[n] = f"MART_SPECIALTIES_ID_KANTO_{n}"
        return self.marts[n]

    def warp(self, args):
        """Warp map, 0, x, z, direction (HGSS) -> Warp header, x, z, direction."""
        if args[0] not in self.kanto_maps:
            raise Unsupported(f"warp to {args[0]}")
        header, world = self.kanto_maps[args[0]]
        out = []
        coords = []
        for value, offset in ((args[2], WORLD_OFFSET_X), (args[3], WORLD_OFFSET_Z)):
            if not world:
                coords.append(self.value(value))
            elif re.fullmatch(r"\d+", value):
                coords.append(str(int(value) - offset))
            else:
                var = self.value(value)
                out.append(f"SubVar {var}, {offset}")
                coords.append(var)
        return out + [f"Warp {header}, {coords[0]}, {coords[1]}, {self.value(args[4])}"]


# ---------------------------------------------------------------------------
class ScriptsImporter:
    def __init__(self, hg):
        self.hg = Path(hg)
        headers = load_headers(self.hg)
        self.kanto = [h for h in headers if h["regionNo"] == "MAP_REGION_KANTO"]
        self.sprites = json.loads((HERE / "kanto_sprites.json").read_text())
        self.free = self.free_vars_flags()
        self.names = Names(self.hg, {k: v for k, v in self.sprites.items() if v}, self.free)
        self.names.kanto_maps = {h["name"]: (header_name(h["name"]), matrix_key(h["matrixId"]) == "0000_EVERYWHERE") for h in self.kanto}
        self.translator = Translator(self.names)
        self.hidden_items = self.read_hidden_items()
        self.item_balls = self.read_item_balls()
        self.items = set(read_lines(PL / "generated/items.txt"))
        self.hgss_items = {v: k for k, v in hgss_defines(self.hg / "include/constants/items.h").items() if k.startswith("ITEM_")}
        self.visible_items = []   # (label, item, quantity)
        self.kanto_hidden = []    # (item, quantity)

    # ------------------------------------------------------------ free names
    def free_vars_flags(self):
        """Platinum flags and vars that only Sinnoh's map scripts and events use."""
        lines = read_lines(PL / "generated/vars_flags.txt")
        hdr = (PL / "include/data/map_headers.h").read_text()
        sinnoh = set(re.findall(r"(?:scriptsArchiveID|initScriptsArchiveID) = (scripts_\w+)", hdr))
        sinnoh_events = set(re.findall(r"eventsArchiveID = (events_\w+)", hdr))
        live = collections.Counter()
        for root in ("src", "include", "asm", "res"):
            for path in (PL / root).rglob("*"):
                if not path.is_file() or path.suffix not in (".c", ".h", ".s", ".inc", ".json", ".txt", ".py"):
                    continue
                stem = path.stem
                if path.suffix == ".s" and "field/scripts" in str(path) and (stem in sinnoh or "kanto" in stem):
                    continue
                if path.suffix == ".json" and "field/events" in str(path) and (stem in sinnoh_events or stem.startswith("kanto_")):
                    continue
                if path.name in ("map_headers.h", "kanto_map_headers.h", "hidden_items.h"):
                    continue
                for m in re.findall(r"\b(?:FLAG|VAR)_\w+", path.read_text(errors="ignore")):
                    live[m] += 1
        start = lines.index(next(l for l in lines if l.startswith("MAP_LOCAL_FLAGS_END")))
        end = lines.index(next(l for l in lines if l.startswith("HIDDEN_ITEM_FLAGS_START")))
        flags = [l for l in lines[start + 1:end] if l.startswith("FLAG_") and "=" not in l and live[l] == 0 and not RESERVED.search(l)]
        vstart = lines.index(next(l for l in lines if l.startswith("MAP_LOCAL_VARS_END")))
        vend = lines.index(next(l for l in lines if l.startswith("SCRIPT_LOCAL_VARS_START")))
        vars_ = [l for l in lines[vstart + 1:vend] if l.startswith("VAR_") and "=" not in l and live[l] == 0
                 and not RESERVED.search(l) and not l.startswith("VAR_OBJ_GFX")]
        return {"flags": flags, "vars": vars_}

    # -------------------------------------------------------------- HGSS data
    def read_hidden_items(self):
        text = (self.hg / "src/data/fieldmap/hidden_items.h").read_text()
        return [(m.group(1), int(m.group(2))) for m in re.finditer(r"\{\s*(ITEM_\w+),\s*(\d+),[^}]*\}", text)]

    def read_item_balls(self):
        """std_itemball_* (7000 + n) -> (item ID, quantity), from scr_seq_0141."""
        text = (self.hg / "files/fielddata/script/scr_seq/scr_seq_0141.s").read_text()
        out = {}
        for m in re.finditer(r"scr_seq_0141_(\d+):\n\tSetVar VAR_SPECIAL_x8008, (\w+)\n\tSetVar VAR_SPECIAL_x8009, (\w+)", text):
            out[int(m.group(1))] = (m.group(2), int(m.group(3), 0))
        return out

    def std_ids(self):
        return hgss_defines(self.hg / "include/constants/std_script.h")

    def pl_item(self, item):
        """HGSS item (name or ID) -> Platinum item name, or None."""
        name = self.hgss_items.get(int(item)) if item.isdigit() else item
        return name if name in self.items else None

    # ----------------------------------------------------------------- events
    def import_events(self):
        std = self.std_ids()
        self.entry_kinds = collections.defaultdict(dict)  # events bank -> {script number: kind}
        self.objects_by_bank = {}
        self.event_report = collections.Counter()
        for bank in sorted({h["eventsBank"] for h in self.kanto}):
            world = any(h["eventsBank"] == bank and matrix_key(h["matrixId"]) == "0000_EVERYWHERE" for h in self.kanto)
            dx, dz = (WORLD_OFFSET_X, WORLD_OFFSET_Z) if world else (0, 0)
            src = self.hg / "files/fielddata/eventdata/zone_event" / (bank.removeprefix("NARC_zone_event_").removesuffix("_bin") + ".json")
            hg_events = json.loads(src.read_text())
            path = EVENTS / f"{events_name(bank)}.json"
            events = json.loads(path.read_text())
            kinds = self.entry_kinds[bank]
            objects = []
            for o in hg_events.get("objects", []):
                objects.append(self.object_event(o, dx, dz, std, kinds))
            self.objects_by_bank[bank] = [o["id"] for o in objects]
            bgs = [b for b in (self.bg_event(b, dx, dz, std, kinds) for b in hg_events.get("bgs", [])) if b]
            coords = []
            for c in hg_events.get("coords", []):
                script = self.script_number(c["scriptId"])
                kinds.setdefault(script, "coord")
                try:
                    var = self.names.var(c["var"])
                except Unsupported:
                    self.event_report["coord with unsupported var"] += 1
                    continue
                coords.append({"script": script, "x": c["x"] - dx, "z": c["z"] - dz, "y": c["y"],
                               "width": c["w"], "length": c["h"], "var": var, "value": c["val"]})
            events.update({"object_events": objects, "bg_events": bgs, "coord_events": coords})
            path.write_text(json.dumps(events, indent=4) + "\n")

    @staticmethod
    def script_number(script_id):
        m = re.fullmatch(r"_EV_scr_seq_\w+_(\d+) \+ 1", str(script_id))
        return int(m.group(1)) + 1 if m else None

    def object_event(self, o, dx, dz, std, kinds):
        script_id = str(o["scriptId"])
        script = self.script_number(script_id)
        trainer_type = "TRAINER_TYPE_NONE"
        sprite = o["spriteId"]
        if script is not None:
            kinds.setdefault(script, "object")
        elif script_id in FIELD_MOVE_OBJECTS:
            script = FIELD_MOVE_OBJECTS[script_id]
        elif script_id.startswith("std_itemball_"):
            script = self.item_ball(std[script_id] - 7000, script_id)
        else:
            # Trainers, apricorn trees and the Pokémon Center's link NPCs.
            self.event_report[f"object with {script_id.split('(')[0]}"] += 1
            script = 0
        try:
            gfx = self.names.name(sprite)
        except Unsupported:
            self.event_report[f"sprite {sprite}"] += 1
            gfx = "OBJ_EVENT_GFX_KANTO_GSMAN1" if "OBJ_EVENT_GFX_KANTO_GSMAN1" in self.sprites.values() else "OBJ_EVENT_GFX_PLAYER_M"
        try:
            flag = self.names.flag(o["eventFlag"])
        except Unsupported:
            self.event_report[f"object flag {o['eventFlag']}"] += 1
            flag = "0"
        movement = o["movement"] if o["movement"] <= LAST_SHARED_MOVEMENT_TYPE else 15
        params = [o["param0"], o["param1"], o["param2"]]
        return {
            "id": o["id"],
            "graphics_id": gfx,
            "movement_type": MOVEMENT_TYPES[movement],
            "trainer_type": trainer_type,
            "hidden_flag": flag,
            "script": script,
            "initial_dir": o["facingDirection"],
            "data": params if any(params) else [],
            "movement_range_x": o["xRange"],
            "movement_range_z": o["yRange"],
            "x": o["x"] - dx,
            "z": o["z"] - dz,
            "y": o["y"] >> 16,  # HGSS stores it as fixed point
        }

    def bg_event(self, b, dx, dz, std, kinds):
        script_id = str(b["scriptId"])
        script = self.script_number(script_id)
        if script is not None:
            kinds.setdefault(script, "bg")
            bg_type = 1 if b["type"] == 1 else 0
        elif script_id.startswith("std_hiddenitem_"):
            script = self.hidden_item(std[script_id] - 8000)
            if script is None:
                return None
            bg_type = 2
        else:
            self.event_report[f"bg with {script_id}"] += 1
            return None
        return {"script": script, "type": bg_type, "x": b["x"] - dx, "z": b["z"] - dz, "y": b["y"],
                "player_facing_dir": BG_DIRS[b["dir"]]}

    def item_ball(self, n, std_name):
        item, qty = self.item_balls[n]
        item = self.pl_item(item)
        if item is None:
            self.event_report["item ball with an item Platinum lacks"] += 1
            return 0
        label = "VisibleItems_Kanto_" + "".join(w.capitalize() for w in std_name.removeprefix("std_itemball_").split("_"))
        self.visible_items.append((label, item, qty))
        return 7000 + self.first_visible_kanto + len(self.visible_items) - 1

    def hidden_item(self, n):
        item, qty = self.hidden_items[n]
        item = self.pl_item(item)
        if item is None:
            self.event_report["hidden item Platinum lacks"] += 1
            return None
        self.kanto_hidden.append((item, qty))
        return 8000 + len(self.kanto_hidden) - 1

    # ---------------------------------------------------------------- scripts
    def import_scripts(self):
        names, init_names = [], []
        self.script_files = {}
        for bank in sorted({h["scriptsBank"] for h in self.kanto}):
            hs = [h for h in self.kanto if h["scriptsBank"] == bank]
            h = hs[0]
            stem = bank.removeprefix("NARC_scr_seq_").removesuffix("_bin")
            gmm = kanto_text.gmm_name(h["msgBank"])
            self.names.messages = self.messages[gmm]
            self.names.objects = set(self.objects_by_bank.get(h["eventsBank"], []))
            world = matrix_key(h["matrixId"]) == "0000_EVERYWHERE"
            ctx = FileContext(stem, (WORLD_OFFSET_X, WORLD_OFFSET_Z) if world else (0, 0), self.entry_kinds[h["eventsBank"]])
            text = (self.hg / "files/fielddata/script/scr_seq" / f"{stem}.s").read_text()
            body, good, stand_ins = self.translator.translate_file(text, ctx)
            name = f"kanto_scripts_{stem.removeprefix('scr_seq_').lower()}"
            includes = ['#include "macros/scrcmd.inc"', f'#include "res/text/bank/{kanto_text.bank_name(gmm)}.h"',
                        f'#include "res/field/events/{events_name(h["eventsBank"])}.h"', "", ""]
            (SCRIPTS / f"{name}.s").write_text("\n".join(includes + body) + "\n")
            names.append(name)
            for hh in hs:
                self.script_files[hh["name"]] = name
            self.stats["entries"] += good
            self.stats["stand-ins"] += stand_ins
        self.init_files = {}
        for bank in sorted({h["scriptHeaderBank"] for h in self.kanto}):
            stem = bank.removeprefix("NARC_scr_seq_").removesuffix("_bin")
            name = f"kanto_scripts_init_{stem.removeprefix('scr_seq_').lower()}"
            text = (self.hg / "files/fielddata/script/scr_seq" / f"{stem}.s").read_text()
            (SCRIPTS / f"{name}.s").write_text(self.init_script(text) + "\n")
            init_names.append(name)
            for h in self.kanto:
                if h["scriptHeaderBank"] == bank:
                    self.init_files[h["name"]] = name
        update_meson_files(SCRIPTS / "meson.build", "s", [f"{n}.s" for n in names + init_names])
        update_order(SCRIPTS / "scripts.order", names + init_names)

    def init_script(self, text):
        out = ['#include "macros/scrcmd.inc"', "", ""]
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith(("#", ".")):
                continue
            line = re.sub(r"_EV_scr_seq_\w+_(\d+) \+ 1", lambda m: str(int(m.group(1)) + 1), line)
            if line.endswith(":"):
                out.append(line)
                continue
            cmd, _, rest = line.partition(" ")
            if "std_" in rest:
                # HGSS's Pokémon Center link rooms (wireless, Wi-Fi, the Pokégear).
                self.stats["init scripts dropped"] += 1
                continue
            if cmd == "InitScriptGoToIfEqual":
                var, value, script = [a.strip() for a in rest.split(",")]
                try:
                    var = self.names.value(var)
                    value = self.names.value(value)
                except Unsupported:
                    self.stats["init checks dropped"] += 1
                    continue
                out.append(f"    InitScriptGoToIfEqual {var}, {value}, {script}")
            else:
                out.append(f"    {line}")
        return "\n".join(out)

    # ----------------------------------------------------------------- tables
    def write_visible_items(self):
        path = SCRIPTS / "scripts_visible_items.s"
        lines = path.read_text().splitlines()
        lines = [l for l in lines if "VisibleItems_Kanto_" not in l]
        text = "\n".join(lines)
        text = re.sub(r"\n\nVisibleItems_Kanto_\w+:\n(    .*\n)+", "\n", text)
        lines = text.splitlines()
        end = lines.index("    ScriptEntryEnd")
        lines[end:end] = [f"    ScriptEntry {label}" for label, _, _ in self.visible_items]
        body = []
        for label, item, qty in self.visible_items:
            body += ["", f"{label}:", f"    SetVar VAR_0x8008, {item}", f"    SetVar VAR_0x8009, {qty}",
                     "    GoTo VisibleItems_TryGiveItem", "    End"]
        at = len(lines) - 1 if lines[-1].strip() == ".balign 4, 0" else len(lines)
        while at > 0 and not lines[at - 1].strip():
            at -= 1
        lines[at:at] = body
        path.write_text("\n".join(lines) + "\n")

    def count_visible_items(self):
        text = (SCRIPTS / "scripts_visible_items.s").read_text()
        return len([l for l in text.splitlines() if l.startswith("    ScriptEntry ") and "Kanto" not in l])

    def write_hidden_items(self):
        """Kanto's hidden items take the hidden item flags from the start."""
        entries = "".join(f"    HIDDEN_ITEM_ENTRY({item}, {qty}, 2, HIDDEN_ITEM_FLAGS_START + {i}),\n"
                          for i, (item, qty) in enumerate(self.kanto_hidden))
        (PL / "include/data/field/kanto_hidden_items.h").write_text(
            "// Generated by tools/hgss_import/import_kanto_scripts.py, do not edit.\n"
            "// Kanto's hidden items, from HGSS: hidden item script 8000 + n.\n" + entries)

    def write_marts(self):
        hg = (self.hg / "src/scrcmd_mart.c").read_text()
        lists = dict(re.findall(r"const u16 (_\w+)\[\] = \{([^}]*)\}", hg))
        order = re.search(r"const u16 \*_0210FA3C\[\] = \{([^}]*)\}", hg).group(1).replace(",", " ").split()
        ids = read_lines(PL / "generated/mart_specialties_id.txt")
        ids = [i for i in ids if not i.startswith("MART_SPECIALTIES_ID_KANTO_")]
        defs, entries = [], []
        for n in sorted(self.names.marts):
            items = [i.strip() for i in lists[order[n]].split(",") if i.strip() and i.strip() != "0xFFFF"]
            items = [i for i in (self.pl_item(i) for i in items) if i]
            defs.append(f"static const u16 sKantoMart{n}[] = {{ {', '.join(items + ['SHOP_ITEM_END'])} }};")
            entries.append(f"    [{self.names.marts[n]}] = sKantoMart{n}, \\")
            ids.append(self.names.marts[n])
        (PL / "generated/mart_specialties_id.txt").write_text("\n".join(ids) + "\n")
        (PL / "include/data/kanto_marts.h").write_text(
            "// Generated by tools/hgss_import/import_kanto_scripts.py, do not edit.\n"
            "// Kanto's specialty marts, from HGSS.\n\n" + "\n".join(defs) + "\n\n#define KANTO_MART_SPECIALTIES \\\n"
            + "\n".join(entries) + "\n\n")

    def write_new_game_flags(self):
        """Kanto's flags that HGSS sets when a game starts."""
        text = (self.hg / "files/fielddata/script/scr_seq/scr_seq_0149.s").read_text()
        sets = []
        for flag in re.findall(r"SetFlag (FLAG_\w+)", text):
            if flag in self.names.flag_map and self.names.flag_map[flag] != "0":
                sets.append(f"    SetFlag {self.names.flag_map[flag]}")
        path = SCRIPTS / "scripts_init_new_game.s"
        lines = path.read_text().splitlines()
        if GENERATED_BEGIN in lines:
            del lines[lines.index(GENERATED_BEGIN):lines.index(GENERATED_END) + 1]
        end = max(i for i, l in enumerate(lines) if l.strip() == "End")
        lines[end:end] = [GENERATED_BEGIN] + sets + [GENERATED_END]
        path.write_text("\n".join(lines) + "\n")

    def update_headers(self):
        path = PL / "include/data/kanto_map_headers.h"
        text = path.read_text()
        for h in self.kanto:
            start = text.index(f"    [{header_name(h['name'])}] = {{")
            end = text.index("    },", start)
            entry = text[start:end]
            entry = re.sub(r"\.scriptsArchiveID = \w+,", f".scriptsArchiveID = {self.script_files[h['name']]},", entry)
            entry = re.sub(r"\.initScriptsArchiveID = \w+,", f".initScriptsArchiveID = {self.init_files[h['name']]},", entry)
            entry = re.sub(r"\.msgArchiveID = \w+,", f".msgArchiveID = {kanto_text.bank_const(kanto_text.gmm_name(h['msgBank']))},", entry)
            text = text[:start] + entry + text[end:]
        path.write_text(text)

    # -------------------------------------------------------------------- run
    def run(self):
        self.stats = collections.Counter()
        gmms = sorted({kanto_text.gmm_name(h["msgBank"]) for h in self.kanto})
        kanto_text.import_text(self.hg, gmms)
        kanto_signs.import_signs(self.hg)
        self.messages = {g: set(re.findall(r'id="(\w+)"', (self.hg / "files/msgdata/msg" / f"{g}.gmm").read_text())) for g in gmms}
        self.first_visible_kanto = self.count_visible_items()
        self.import_events()
        self.import_scripts()
        self.write_visible_items()
        self.write_hidden_items()
        self.write_marts()
        self.write_new_game_flags()
        self.update_headers()
        (HERE / "kanto_vars_flags.json").write_text(json.dumps({"flags": self.names.flag_map, "vars": self.names.var_map}, indent=2) + "\n")
        report = [f"{n}: {e}: {', '.join(why)}" for n, e, why in self.translator.report]
        (HERE / "kanto_scripts_report.txt").write_text(
            "# Script entries replaced by a stand-in, and why (generated by import_kanto_scripts.py).\n" + "\n".join(report) + "\n")
        print(dict(self.stats))
        print(dict(self.event_report))
        print("unknown names:", self.names.unsupported_names.most_common(40))
        reasons = collections.Counter(w for _, _, why in self.translator.report for w in why)
        print("stand-in reasons:", reasons.most_common(60))


MOVEMENT_TYPES = read_lines(PL / "generated/movement_types.txt")
BG_DIRS = read_lines(PL / "generated/bg_event_dirs.txt")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("hgss", help="path to a pokeheartgold checkout")
    ScriptsImporter(parser.parse_args().hgss).run()


if __name__ == "__main__":
    main()
